language: nix
script:
  - set -o pipefail
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - "[[ -v NIXPKGS_CHANNEL ]] && ARG=\"--argstr nixpkgsCommit $NIXPKGS_CHANNEL\" || :"
  - nix-build -A nix-linter $ARG | (if [[ "$TRAVIS_BRANCH" = "master" ]]; then cachix push nix-linter; fi)
env: # Alllow for failures
matrix:
  include:
    - name: "Default build"
    - name: "NixOS 18.09"
      env: NIXPKGS_CHANNEL=nixos-18.09
    - name: "Nixpkgs Unstable"
      env: NIXPKGS_CHANNEL=nixpkgs-unstable
  allow_failures:
    - env: NIXPKGS_CHANNEL=nixpkgs-unstable
  fast_finish: true
before_deploy: "./update_readme.sh"
deploy:
  provider: pages
  target-branch: master
  keep-history: true
  skip-cleanup: true
  on:
    branch: master
    condition:
      - '! -v NIXPKGS_CHANNEL '
      # Check this, so we don't get a deploy loop
      - '$(git log -1 --pretty=format:"%ae") != "deploy@travis-ci.org"'
  file:
    README.md
  github_token:
    secure: IhhPdLSMuKEQDPmHheB1zvoFKTUT+lqKrkwbv6Pih7hbPKjtX2Y1VmBAGjfQRlXSz5876DAqYFNHe/avIvtkEMvnI0p24e5IWb1O5H/lNS3TpcmIF23umMDkJVbWXsP7qdBei1YGN/7Tr/IUZNZ+RD8VUR9SL1ozL6QNIvqFR6zqMFDlYCNkRMlQ3usO8NkBPaI+4WjhB3t8tlGJN9/r1CIizfLIE0g32v23RGCOV3gRNzS/M5Cb/ZfpC/6DyjjMkBUVrDAlxPOK/PO5Zn7xRycRUX5AlhO413FMfPX59lm/zWp+JJUJ5M/CZL4AqaUysl2IppBZPJzNlkRiYM0/V/ET328rPYvlzyOtr2rN+tjSv4x3dDw4t6Tt+QRlSyfkUn9kpcwijEf4pV8SrKAKSEBi7cHkyf4xq1f+dBEDBlj1I0rZ8nax3DNp2mL3DKrzX0PLZgVJzWKohbFXjCcWYl+o3XAnjjBvanxmjwB28i8rmlokc1lDSe84bunRi1vjmT5snEddgmPpPieRHr71seF7ixTLT1qW6Qa+JraT+cpQZcjoMr8BSyv+XeVK/Pk+wyuOIKnxBANMB7jevkGJVUazCEtxajOHbXhVGyG0qzfp9chNYxqWvYlbOXiHKgg1DRp++yxvBfp4Y0KwJFikTCidWwAIbnsfmKQdpjxblo4=
